/* A RapidNet application. Generated by RapidNet compiler. */

#include "mytest.h"
#include <cstdlib>
#include "ns3/nstime.h"
#include "ns3/simulator.h"
#include "ns3/type-ids.h"
#include "ns3/rapidnet-types.h"
#include "ns3/rapidnet-utils.h"
#include "ns3/assignor.h"
#include "ns3/selector.h"
#include "ns3/rapidnet-functions.h"

using namespace std;
using namespace ns3;
using namespace ns3::rapidnet;
using namespace ns3::rapidnet::mytest;

const string Mytest::EPING = "ePing";
const string Mytest::EPINGPONGFINISH = "ePingPongFinish";
const string Mytest::EPONG = "ePong";
const string Mytest::TLINK = "tLink";

NS_LOG_COMPONENT_DEFINE ("Mytest");
NS_OBJECT_ENSURE_REGISTERED (Mytest);

TypeId
Mytest::GetTypeId (void)
{
  static TypeId tid = TypeId ("ns3::rapidnet::mytest::Mytest")
    .SetParent<RapidNetApplicationBase> ()
    .AddConstructor<Mytest> ()
    ;
  return tid;
}

Mytest::Mytest()
{
  NS_LOG_FUNCTION_NOARGS ();
}

Mytest::~Mytest()
{
  NS_LOG_FUNCTION_NOARGS ();
}

void
Mytest::DoDispose (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::DoDispose ();
}

void
Mytest::StartApplication (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StartApplication ();
  RAPIDNET_LOG_INFO("Mytest Application Started");
}

void
Mytest::StopApplication ()
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StopApplication ();
  RAPIDNET_LOG_INFO("Mytest Application Stopped");
}

void
Mytest::InitDatabase ()
{
  //RapidNetApplicationBase::InitDatabase ();

  AddRelationWithKeys (TLINK, attrdeflist (
    attrdef ("tLink_attr1", IPV4),
    attrdef ("tLink_attr2", IPV4)));

}

void
Mytest::DemuxRecv (Ptr<Tuple> tuple)
{
  RapidNetApplicationBase::DemuxRecv (tuple);

  if (IsInsertEvent (tuple, TLINK))
    {
      R1Eca0Ins (tuple);
    }
  if (IsRecvEvent (tuple, EPING))
    {
      R2_eca (tuple);
    }
  if (IsRecvEvent (tuple, EPONG))
    {
      R3_eca (tuple);
    }
}

void
Mytest::R1Eca0Ins (Ptr<Tuple> tLink)
{
  RAPIDNET_LOG_INFO ("R1Eca0Ins triggered");

  Ptr<Tuple> result = tLink;

  result = result->Project (
    EPING,
    strlist ("tLink_attr2",
      "tLink_attr1",
      "tLink_attr2"),
    strlist ("ePing_attr1",
      "ePing_attr2",
      RN_DEST));

  Send (result);
}

void
Mytest::R2_eca (Ptr<Tuple> ePing)
{
  RAPIDNET_LOG_INFO ("R2_eca triggered");

  Ptr<Tuple> result = ePing;

  result = result->Project (
    EPONG,
    strlist ("ePing_attr2",
      "ePing_attr1",
      "ePing_attr2"),
    strlist ("ePong_attr1",
      "ePong_attr2",
      RN_DEST));

  Send (result);
}

void
Mytest::R3_eca (Ptr<Tuple> ePong)
{
  RAPIDNET_LOG_INFO ("R3_eca triggered");

  Ptr<Tuple> result = ePong;

  result = result->Project (
    EPINGPONGFINISH,
    strlist ("ePong_attr1"),
    strlist ("ePingPongFinish_attr1"));

  SendLocal (result);
}

