## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('mytest', ['internet-stack'])
    module.source = [
        'mytest.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'mytest'
    headers.source = [
        'mytest.h',
        'mytest-helper.h',
        ]
