## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('bgpblackhole', ['internet-stack'])
    module.source = [
        'bgpblackhole.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'bgpblackhole'
    headers.source = [
        'bgpblackhole.h',
        'bgpblackhole-helper.h',
        ]
