################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
utils \
src/simulator \
src/routing/static-routing \
src/routing/olsr \
src/routing/list-routing \
src/routing/global-routing \
src/rapidnet-compiler \
src/rapidnet/values \
src/rapidnet \
src/rapidnet/tests \
src/node \
src/mobility \
src/l4-platform \
src/internet-stack \
src/helper \
src/devices/wifi \
src/devices/virtual-net-device \
src/devices/tap-bridge \
src/devices/point-to-point \
src/devices/emu \
src/devices/csma \
src/devices/bridge \
src/core \
src/contrib \
src/contrib/stats \
src/common \
src/applications/v4ping \
src/applications/udp-echo \
src/applications/sim-ls-triggered \
src/applications/sim-ls-periodic \
src/applications/sim-hsls-triggered \
src/applications/sim-hsls-periodic \
src/applications/secure-simple-bgp \
src/applications/secure-pingpong \
src/applications/secure-pathvector \
src/applications/reachable2 \
src/applications/reachable \
src/applications/pktfwd-prov \
src/applications/pingpong-l4 \
src/applications/pingpong \
src/applications/pathvector2 \
src/applications/pathvector-prov \
src/applications/pathvector \
src/applications/packet-sink \
src/applications/onoff \
src/applications/mincost-query \
src/applications/mincost-prov \
src/applications/epidemic \
src/applications/emu-ls-triggered \
src/applications/emu-ls-periodic \
src/applications/emu-hsls-triggered \
src/applications/emu-hsls-periodic \
src/applications/dsr \
src/applications/discovery-epidemic \
src/applications/discovery \
src/applications/chord \
scratch \
scratch/multiple-sources \
samples \
examples \
examples/stats \
build/debug/utils \
build/debug/src/simulator \
build/debug/src/routing/static-routing \
build/debug/src/routing/olsr \
build/debug/src/routing/list-routing \
build/debug/src/routing/global-routing \
build/debug/src/rapidnet-compiler \
build/debug/src/rapidnet/values \
build/debug/src/rapidnet \
build/debug/src/rapidnet/tests \
build/debug/src/node \
build/debug/src/mobility \
build/debug/src/l4-platform \
build/debug/src/internet-stack \
build/debug/src/helper \
build/debug/src/devices/wifi \
build/debug/src/devices/virtual-net-device \
build/debug/src/devices/tap-bridge \
build/debug/src/devices/point-to-point \
build/debug/src/devices/emu \
build/debug/src/devices/csma \
build/debug/src/devices/bridge \
build/debug/src/core \
build/debug/src/contrib \
build/debug/src/contrib/stats \
build/debug/src/common \
build/debug/src/applications/v4ping \
build/debug/src/applications/udp-echo \
build/debug/src/applications/sim-ls-triggered \
build/debug/src/applications/sim-ls-periodic \
build/debug/src/applications/sim-hsls-triggered \
build/debug/src/applications/sim-hsls-periodic \
build/debug/src/applications/secure-simple-bgp \
build/debug/src/applications/secure-pingpong \
build/debug/src/applications/secure-pathvector \
build/debug/src/applications/reachable2 \
build/debug/src/applications/reachable \
build/debug/src/applications/pktfwd-prov \
build/debug/src/applications/pingpong-l4 \
build/debug/src/applications/pingpong \
build/debug/src/applications/pathvector2 \
build/debug/src/applications/pathvector-prov \
build/debug/src/applications/pathvector \
build/debug/src/applications/packet-sink \
build/debug/src/applications/onoff \
build/debug/src/applications/mincost-query \
build/debug/src/applications/mincost-prov \
build/debug/src/applications/epidemic \
build/debug/src/applications/emu-ls-triggered \
build/debug/src/applications/emu-ls-periodic \
build/debug/src/applications/emu-hsls-triggered \
build/debug/src/applications/emu-hsls-periodic \
build/debug/src/applications/dsr \
build/debug/src/applications/discovery-epidemic \
build/debug/src/applications/discovery \
build/debug/src/applications/chord \
build/debug/scratch \
build/debug/scratch/multiple-sources \
build/debug/samples \
build/debug/examples \
build/debug/examples/stats \
build/.conf_check_0/testbuild/debug \
build/.conf_check_0 \
bindings/python \

