## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('bgpofflink', ['internet-stack'])
    module.source = [
        'bgpofflink.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'bgpofflink'
    headers.source = [
        'bgpofflink.h',
        'bgpofflink-helper.h',
        ]
