## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('bogonlist', ['internet-stack'])
    module.source = [
        'bogonlist.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'bogonlist'
    headers.source = [
        'bogonlist.h',
        'bogonlist-helper.h',
        ]
